server.port: 8080
spring:
  application.name: api-gateway
  config.import: vault://
  cloud:
    vault:
      uri: ${VAULT_ADDR:http://vault:8200}
      authentication: APPROLE
      app-role.role-id: ${API_GATEWAY_VAULT_ROLE_ID}
      app-role.secret-id: ${API_GATEWAY_VAULT_SECRET_ID}
      kv.backend: secret
      kv.default-context: api-gateway
    gateway:
      routes:
        - id: links
          uri: http://link-service:8081
          predicates: [ Path=/api/links/** ]
          filters: [ RewritePath=/api/links/(?<segment>.*), /${segment} ]
        - id: redirect
          uri: http://redirect-service:8082
          predicates: [ Path=/r/** ]
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 15
                redis-rate-limiter.burstCapacity: 30
                key-resolver: "#{@ipKeyResolver}"
        - id: analytics
          uri: http://analytics-service:8083
          predicates: [ Path=/api/analytics/** ]
          filters: [ RewritePath=/api/analytics/(?<segment>.*), /analytics/${segment} ]
      redis-rate-limiter:
        replenishRate: 20
        burstCapacity: 40
  security.oauth2.resourceserver.jwt.issuer-uri: ${JWT_ISSUER_URI:http://auth-server:9000}
  data.redis.host: redis
management.endpoints.web.exposure.include: health,info
