server:
  port: 8081
spring:
  application.name: link-service
  config.import: vault://
  cloud.vault:
    uri: ${VAULT_ADDR:http://vault:8200}
    authentication: APPROLE
    app-role.role-id: ${LINK_SERVICE_VAULT_ROLE_ID}
    app-role.secret-id: ${LINK_SERVICE_VAULT_SECRET_ID}
    kv.backend: secret
    kv.default-context: link-service
  datasource:
    url: jdbc:postgresql://postgres:5432/url_shortener?currentSchema=${links.db.schema:links_schema}
    username: ${links.db.username}
    password: ${links.db.password}
  jpa:
    hibernate.ddl-auto: validate
    properties.hibernate.default_schema: ${links.db.schema:links_schema}
  flyway:
    schemas: ${links.db.schema:links_schema}
    default-schema: ${links.db.schema:links_schema}
  security.oauth2.resourceserver.jwt.issuer-uri: ${JWT_ISSUER_URI:http://auth-server:9000}
management.endpoints.web.exposure.include: health,info
